### PR TITLE
Semicircle

### PR DESCRIPTION
**Pull request by PenetratingShot**
@talonbragg, can you review the code for semicircle before we push to master? I just want to make sure that nothing is wrong before merging...

### CODE REVIEW

**Comment by talonbragg** [comment]
Ok

**Comment by talonbragg** [comment]
Woops

**Comment by PenetratingShot** [comment]
Thanks, I'll test it out when I get home, update the gzipped, build it, and then publish 0.1.1

**Comment by PenetratingShot** [comment]
@talonbragg, is version 0.1.1 ok or do you want it to be something else?

**Pull request merged**
